# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5753e9884588a461af22a2db8cf8ec2e652b96fc79de13ddd179d2e9d0328478dad69e810231d98f46e0782d87ca10fcfdf6f173d361330f04c2afe06c24a167

test:
  secret_key_base: 984881cc89d893ae5f743a254fe513427d583e212f118e6240260052686ef20a42e529b41b036380bce141ee177a3dd6f1773ddac8cabf4d26ecf1ecdb616ff4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
